#!/bin/bash

ls > file
$1 file

ls > file
$1 file

mkdir dir
man ls > dir/man
mkdir dir/mandir
man cp > dir/mandir/cp
$1 dir

mkdir dir
man ls > dir/man
mkdir dir/mandir
man cp > dir/mandir/cp
$1 dir

ls > file2
cat test > file3
$1 file2 file3

mkdir dir2
cat test > dir2/file4
ls > file2
ls > file3
$1 dir2 file2 file3
